oa3_spec: https://raw.githubusercontent.com/pagopa/pagopa-gps-donation-service/pasqualespica-patch-opex/openapi/openapi.json
name: DEV Dash GPS service
location: West Europe
timespan: 5m
resources:
  - /subscriptions/bbe47ad4-08b3-4925-94c5-1278e5819b86/resourceGroups/pagopa-d-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-d-app-gw
