microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-spontaneous-payments
    tag: "0.1.12-PIDM-491-workload-identity" #improve
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.gps.internal.uat.platform.pagopa.it"
    path: /pagopa-spontaneous-payments-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "gps-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.3"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: "pagopaspontaneouspayments" # required to show cloud role name in application insights
    COSMOS_URI: https://pagopa-u-weu-gps-cosmos-account.documents.azure.com:443/
    COSMOS_DATABASE: "db"
    COSMOS_QUERY_METRICS: "false"
    EC_CONTAINER_NAME: "creditor_institutions"
    SERVICE_CONTAINER_NAME: "services"
    GPD_HOST: https://api.uat.platform.pagopa.it/gpd/api/v1
    IUV_GENERATOR_HOST: https://api.uat.platform.pagopa.it/shared/pagopa-iuvgenerator/v1
    AUX_DIGIT: "3"
    CONNECTION_TIMEOUT: "1500"
    RETRY_GPD_MAX_ATTEMPTS: "1"
    RETRY_GPD_MAX_DELAY: "500"
    RETRY_IUV_GENERATOR_MAX_ATTEMPTS: "1"
    RETRY_IUV_GENERATOR_MAX_DELAY: "300"
    RETRY_EXT_SERVICE_MAX_ATTEMPTS: "1"
    RETRY_EXT_SERVICE_MAX_DELAY: "300"
    LOGGING_LEVEL: "INFO"
  envSecret:
    COSMOS_KEY: cosmos-gps-weu-u-pkey
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
    API_KEY_IUV_GENERATOR: "apikey-iuv-generator"
    API_KEY_EXTERNAL_SERVICE: "apikey-spontaneous-payments-services"
  keyvault:
    name: "pagopa-u-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
